[theme]
base="dark"
primaryColor="#22c55e"     # verde TerraSynapse
backgroundColor="#0F172A"  # azul-escuro sofisticado
secondaryBackgroundColor="#0B1320"
textColor="#E5E7EB"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
