[env]
MODE = "prod"

[api]
API_BASE_URL_PROD = "https://terrasynapse-backend.onrender.com"
API_BASE_URL_DEV  = "https://terrasynapse-backend-dev.onrender.com"  # opcional

[geo]
DEFAULT_LAT = -18.5880
DEFAULT_LON = -49.5690
DEFAULT_CITY = "Capinópolis"
DEFAULT_STATE = "MG"

[openweather]
API_KEY = "fa5b506b2f5299a6617bc5ac2ccc2f58"

[admin]
EMAILS = "terrasynapse@terrasynapse.com"
