# TerraSynapse V2.0 - Streamlit Secrets
# Coloque este arquivo em: frontend/.streamlit/secrets.toml

[api]
# API do backend local
API_BASE_URL = "http://localhost:8000"

# APIs externas (substitua pelas suas chaves reais)
OPENWEATHER_API_KEY = "sua_chave_aqui"
NASA_API_KEY = "sua_chave_aqui"
COMMODITIES_API_KEY = "sua_chave_aqui"

[database]
# Se usar banco de dados no futuro
DATABASE_URL = "sqlite:///terrasynapse.db"

[cache]
# Configurações de cache
REDIS_URL = "redis://localhost:6379"
# --- TerraSynapse: localização padrão do site ---
[site]
name = "Fazenda São João"
lat = -23.5505      # coloque a latitude real da propriedade (ex.: -21.1767)
lon = -46.6333      # coloque a longitude real da propriedade (ex.: -47.8060)
timezone = "auto"   # pode deixar "auto" ou usar "America/Sao_Paulo"

# --- APIs que estas páginas vão usar agora ---
[apis]
# NDVI (opcional). Deixe vazio agora; quando pegar a chave/polígono, preencha:
agromon_key = ""
polygon_id  = ""
