# TerraSynapse V2.0 - Streamlit Secrets

[api]
# URL pública do backend no Render
API_BASE_URL = "https://terrasynapse-backend.onrender.com"

# (opcional) chaves de serviços externos se usar direto no frontend
OPENWEATHER_API_KEY = "fa5b506b2f5299a6617bc5ac2ccc2f58"
NASA_API_KEY = ""
COMMODITIES_API_KEY = ""

[geo]
DEFAULT_LAT = -18.6800
DEFAULT_LON = -49.5660
DEFAULT_CITY = "Fazenda São João"
DEFAULT_STATE = "GO"
