# TerraSynapse V2.0 - Streamlit Secrets
# Coloque este arquivo em: frontend/.streamlit/secrets.toml

[api]
# API do backend local
API_BASE_URL = "http://localhost:8000"

# APIs externas (substitua pelas suas chaves reais)
OPENWEATHER_API_KEY = "sua_chave_aqui"
NASA_API_KEY = "sua_chave_aqui"
COMMODITIES_API_KEY = "sua_chave_aqui"

[database]
# Se usar banco de dados no futuro
DATABASE_URL = "sqlite:///terrasynapse.db"

[cache]
# Configurações de cache
REDIS_URL = "redis://localhost:6379"